- defaults:
    link:
      relink: true

- clean: ["~"]

- link:
    ~/.wakatime.cfg: .wakatime.cfg
    ~/.config/ghostty:
      create: true
      path: ghostty
    ~/.config/base16-shell:
      create: true
      path: .base16-shell
    ~/.config/nvim:
      create: true
      path: nvim
    ~/.config/starship.toml:
      create: true
      path: starship.toml
    ~/.config/atuin:
      create: true
      path: atuin
    ~/.ripgreprc: ripgrep
    ~/.gitconfig: gitconfig
    ~/.zshrc: zshrc
    ~/Library/Application Support/lazygit/config.yml:
      create: true
      path: lazygit.yml
    ~/.claude/skills:
      create: true
      path: claude/skills
    ~/.claude/CLAUDE.md:
      create: true
      path: claude/CLAUDE.md

- shell:
    - [git submodule update --init --recursive, Installing submodules]
