- defaults:
    link:
      relink: true

- clean: ["~"]

- link:
    ~/.wakatime.cfg: .wakatime.cfg
    ~/.config/kitty:
      create: true
      path: kitty
    ~/.config/ghostty:
      create: true
      path: ghostty
    ~/.config/base16-shell:
      create: true
      path: .base16-shell
    ~/.config/nvim:
      create: true
      path: nvim
    ~/.config/starship.toml:
      create: true
      path: starship.toml
    ~/.ripgreprc: ripgrep
    ~/.config/tmuxinator:
      create: true
      path: tmuxinator
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.zshrc: zshrc
    ~/Library/Application Support/lazygit/config.yml:
      create: true
      path: lazygit.yml

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [
        ~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1,
        Installing tmux plugins,
      ]
