experimental_use_rmcp_client = true
sandbox_mode = "workspace-write"
tool_output_token_limit = 15000
approval_policy = "on-failure"
web_search = "live"
personality = "pragmatic"

[features]
shell_snapshot = true
steer = true
collab = true
multi_agent = true

[projects."/Users/psteinroe/Developer"]
trust_level = "trusted"
